development:
  app_name: My Shipit
  secret_key_base: #{SecureRandom.hex(64)}
  host: 'http://localhost:3000'
  redis_url: redis://redis:6379
  default_merge_method: squash
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id:
      secret:
      # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team

test:
  app_name: My Shipit
  secret_key_base: #{SecureRandom.hex(64)}
  host: 'http://localhost:4000'
  redis_url: redis://localhost
  default_merge_method: squash
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team

production:
  app_name: My Shipit
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['SHIPIT_HOST'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  default_merge_method: squash
  github:
    domain: # defaults to github.com
    app_id: <%= ENV['GITHUB_APP_ID'] %>
    installation_id: <%= ENV['GITHUB_INSTALLATION_ID'] %>
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team
  env:
    # SSH_AUTH_SOCK: /foo/bar # You can set environment variable that will be present during deploys.